# Generated by Django 5.1.3 on 2026-02-16 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField()),
                ('data_finalizacao', models.DateTimeField(auto_now_add=True)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.exame')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.clinica')),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.paciente'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('1', 'Tutor'), ('2', 'Recepcionista'), ('3', 'Veterinario'), ('4', 'Gestor')], max_length=1)),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=50)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.clinica')),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='usuario_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exame_tutor', to='base.usuario'),
        ),
        migrations.AddField(
            model_name='exame',
            name='usuario_veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exame_veterinario', to='base.usuario'),
        ),
    ]
