# Generated by Django 5.1.3 on 2026-02-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='accession_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='instituicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='medico_solicitante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='status',
            field=models.CharField(default='recebido', max_length=30),
        ),
        migrations.AddField(
            model_name='exame',
            name='study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='study_id',
            field=models.TextField(default='default_temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame',
            name='study_instance_uid',
            field=models.CharField(default='default_temp', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame',
            name='study_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default='default_temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='texto',
            field=models.TextField(),
        ),
    ]
