# Generated by Django 5.1.3 on 2026-02-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_exame_accession_number_exame_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='study_id',
        ),
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='usuario_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_tutor', to='base.usuario'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='usuario_veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_veterinario', to='base.usuario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raca',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default='Indefinido', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
