# Generated by Django 5.1.3 on 2026-03-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_exame_study_id_alter_clinica_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.clinica'),
        ),
    ]
