# Generated by Django 5.1.3 on 2026-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_usuario_gmail_remove_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='pdf',
            field=models.FileField(blank=True, upload_to='laudos/'),
        ),
    ]
