# Generated by Django 5.1.3 on 2026-03-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_exame_codigo_acesso_exame_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='clinica',
        ),
    ]
