# Generated by Django 5.1.3 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_exame_clinica_remove_usuario_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='laudo_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
