# Generated by Django 5.1.3 on 2026-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_exame_laudo_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='orthanc_instance_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
