# Generated by Django 5.1.3 on 2026-03-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_exame_orthanc_instance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='codigo_acesso',
        ),
    ]
