# Generated by Django 5.1.3 on 2026-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_exame_codigo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
