# Generated by Django 5.1.3 on 2026-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_exame_codigo_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='orthanc_instance_id',
        ),
        migrations.AddField(
            model_name='exame',
            name='orthanc_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
