# Generated by Django 5.1.3 on 2026-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_exame_orthanc_instance_id_exame_orthanc_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modelo_modelo',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
