# Generated by Django 5.1.3 on 2026-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_usuario_modelo_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='modelo_modelo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='comovai',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modelos_laudo',
            field=models.JSONField(default=dict),
        ),
    ]
