# Generated by Django 5.1.3 on 2026-04-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_usuario_modelo_modelo_usuario_comovai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='comovai',
        ),
    ]
