# Generated by Django 5.1.3 on 2026-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_usuario_comovai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='modelos_laudo',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
