# Generated by Django 5.1.3 on 2026-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_usuario_modelos_laudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='modelos_laudo',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
