# Generated by Django 5.1.3 on 2026-04-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_usuario_modelos_laudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('indicacao_clinica', models.TextField(blank=True)),
                ('tecnica', models.TextField(blank=True)),
                ('achados', models.TextField(blank=True)),
                ('impressao_diagnostica', models.TextField(blank=True)),
                ('conclusao', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('comparacao', models.TextField(blank=True)),
                ('limitacoes', models.TextField(blank=True)),
                ('nota_clinica', models.TextField(blank=True)),
                ('assinatura', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_logado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='base.usuario')),
            ],
        ),
    ]
