# Generated by Django 5.1.3 on 2026-04-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='modelos_laudo',
        ),
    ]
