# Generated by Django 5.1.3 on 2026-04-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_usuario_modelos_laudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='nome',
            new_name='campo1',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='achados',
            new_name='campo10',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='assinatura',
            new_name='campo11',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='criado_em',
            new_name='campo12',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='comparacao',
            new_name='campo2',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='conclusao',
            new_name='campo3',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='impressao_diagnostica',
            new_name='campo4',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='indicacao_clinica',
            new_name='campo5',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='limitacoes',
            new_name='campo6',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='nota_clinica',
            new_name='campo7',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='recomendacoes',
            new_name='campo8',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='tecnica',
            new_name='campo9',
        ),
    ]
