# Generated by Django 5.1.3 on 2026-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_nome_modelo_campo1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='campo1',
            new_name='nome_modelo',
        ),
        migrations.AlterField(
            model_name='modelo',
            name='campo12',
            field=models.TextField(blank=True),
        ),
    ]
