# Generated by Django 5.1.3 on 2026-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_campo1_modelo_nome_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('aguardando', 'Aguardando'), ('urgente', 'Urgente')], max_length=10),
        ),
    ]
