# Generated by Django 5.1.3 on 2026-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_exame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='status',
            field=models.CharField(choices=[('Recebido', 'Recebido'), ('Aguardando', 'Aguardando'), ('Urgente', 'Urgente')], max_length=10),
        ),
    ]
