# Generated by Django 5.1.3 on 2026-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_exame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='status',
            field=models.CharField(choices=[('Laudado', 'Laudado'), ('Aguardando', 'Aguardando'), ('Urgente', 'Urgente')], default='Aguardando', max_length=10),
        ),
    ]
