# Generated by Django 5.1.3 on 2026-04-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_exame_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='usuario_tutor',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('V', 'Veterinario'), ('T', 'Tecnico'), ('A', 'Administrador')], max_length=1),
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('cnpj', models.TextField(blank=True)),
                ('exames', models.ManyToManyField(blank=True, related_name='instituicoes', to='base.exame')),
                ('membros_insituticao', models.ManyToManyField(blank=True, related_name='instituicoes', to='base.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='exame',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_instituicao', to='base.instituicao'),
        ),
        migrations.DeleteModel(
            name='Clinica',
        ),
    ]
