# Generated by Django 5.1.3 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_paciente_clinica_remove_exame_usuario_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome_tutor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
