# Generated by Django 5.1.3 on 2026-04-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_paciente_nome_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='instituicao_pertencente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.instituicao'),
        ),
    ]
