# Generated by Django 5.1.3 on 2026-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_usuario_instituicao_pertencente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='membros_insituticao',
            field=models.ManyToManyField(blank=True, null=True, related_name='instituicoes', to='base.usuario'),
        ),
    ]
