# Generated by Django 5.1.3 on 2026-04-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_instituicao_membros_insituticao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='usuario_veterinario',
        ),
        migrations.AddField(
            model_name='exame',
            name='usuario_dicom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_dicom', to='base.usuario'),
        ),
    ]
