# Generated by Django 5.1.3 on 2026-04-16 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_exame_usuario_veterinario_exame_usuario_dicom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='tipo_exame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.clinica')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.exame')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiros', to='base.instituicao')),
            ],
        ),
    ]
