# Generated by Django 5.1.3 on 2026-04-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_clinica_exame_tipo_exame_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='valor',
        ),
        migrations.AddField(
            model_name='exame',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
