# Generated by Django 5.1.3 on 2026-04-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_financeiro_valor_exame_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='valor_a_ser_quitado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
