# Generated by Django 5.1.3 on 2026-04-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_financeiro_valor_a_ser_quitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_a_ser_quitado',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='repasse_a_clinica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exame',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tutor'),
        ),
    ]
