# Generated by Django 5.1.3 on 2026-04-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_tutor_remove_financeiro_valor_a_ser_quitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
