# Generated by Django 5.1.3 on 2026-04-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_exame_tutor_delete_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='exame',
        ),
        migrations.AddField(
            model_name='exame',
            name='financeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.financeiro'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
