# Generated by Django 5.1.3 on 2026-04-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_exame_valor_remove_financeiro_exame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro',
            old_name='repasse_a_clinica',
            new_name='valor_repasse_a_clinica',
        ),
        migrations.AddField(
            model_name='exame',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.modelo'),
        ),
    ]
