# Generated by Django 5.1.3 on 2026-04-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_rename_repasse_a_clinica_financeiro_valor_repasse_a_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='subtipo_exame',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
