# Generated by Django 5.1.3 on 2026-04-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_exame_subtipo_exame_financeiro_forma_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='nome',
            new_name='nome_clinica',
        ),
        migrations.AddField(
            model_name='clinica',
            name='whats_clinica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
