# Generated by Django 5.1.3 on 2026-04-18 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_nome_clinica_nome_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='usuario_logado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.usuario'),
        ),
    ]
