# Generated by Django 5.1.3 on 2026-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_clinica_usuario_logado'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='Veterinario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
