# Generated by Django 5.1.3 on 2026-04-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_exame_veterinario'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarioPedidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='exame',
            name='Veterinario',
        ),
        migrations.AddField(
            model_name='exame',
            name='veterinario_pedidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.veterinariopedidor'),
        ),
    ]
