# Generated by Django 5.1.3 on 2026-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_veterinariopedidor_remove_exame_veterinario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('paciente', models.CharField(max_length=255)),
                ('tutor', models.CharField(blank=True, max_length=255)),
                ('clinica', models.CharField(blank=True, max_length=255)),
                ('tipo_exame', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(blank=True, max_length=100)),
                ('pago', models.BooleanField(default=False)),
                ('enviado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
