# Generated by Django 5.1.3 on 2026-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_lancamentofinanceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='campo1',
            field=models.TextField(blank=True),
        ),
    ]
