# Generated by Django 5.1.3 on 2026-06-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_modelo_campo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='html_conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
