# Generated by Django 5.1.3 on 2026-06-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_modelo_html_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='usuario_logado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='base.usuario'),
        ),
    ]
