# Generated by Django 5.1.3 on 2026-06-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_modelo_usuario_logado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='arquivo_docx',
            field=models.FileField(blank=True, null=True, upload_to='modelos_docx/'),
        ),
    ]
