# Generated by Django 5.1.3 on 2026-06-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_instituicao_arquivo_docx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='arquivo_docx',
        ),
        migrations.AddField(
            model_name='modelo',
            name='arquivo_docx',
            field=models.FileField(blank=True, null=True, upload_to='modelos_docx/'),
        ),
    ]
