# Generated by Django 5.1.3 on 2026-06-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_instituicao_arquivo_docx_modelo_arquivo_docx'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='docx',
            field=models.FileField(blank=True, null=True, upload_to='laudos_docx/'),
        ),
    ]
