# Generated by Django 5.1.3 on 2026-06-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_exame_docx'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='docx',
            field=models.FileField(blank=True, null=True, upload_to='laudos_docx/'),
        ),
    ]
