# Generated by Django 5.1.3 on 2026-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_laudo_docx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='data_laudo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
