# Generated by Django 5.1.3 on 2026-06-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_lancamentofinanceiro_data_laudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='especie',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
