# Generated by Django 5.1.3 on 2026-06-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.especie'),
        ),
    ]
