# Generated by Django 5.1.3 on 2026-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_paciente_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='data_laudo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
