
server{
    listen 443 ssl;
    server_name vizionvet.com.br www.vizionvet.com.br;
    client_max_body_size 500M;
    ssl_certificate /etc/Ngix/certificados/certificado.txt;
    ssl_certificate_key /etc/Ngix/certificados/privatekey.txt;

     location / {
        proxy_pass http://orthanc:8042;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE" always;
        add_header Access-Control-Allow-Headers "*" always;
        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
server{
    listen 80;
    server_name vizionvet.com.br www.vizionvet.com.br;
    return 301 https://$host$request_uri;

}