server {
    listen 80;

    client_max_body_size 500M;

    server_name pacsvisionxvet.conexao46.com.br;

    # =========================
    # DJANGO
    # =========================
    location / {
        proxy_pass http://django-web:8000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # =========================
    # OHIF
    # =========================
    location /viewer/ {
        proxy_pass http://ohif:80/;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;

        rewrite ^/viewer/(.*)$ /$1 break;
    }

    location = /app-config.js {
        proxy_pass http://ohif:80/app-config.js;
    }

    location = /manifest.json {
        proxy_pass http://ohif:80/manifest.json;
    }

    location = /init-service-worker.js {
        proxy_pass http://ohif:80/init-service-worker.js;
    }

    location = /app.bundle.css {
        proxy_pass http://ohif:80/app.bundle.css;
    }

    location ~ ^/app\.bundle\..*\.js$ {
        proxy_pass http://ohif:80;
    }

    location ~* ^/(.*)\.(js|css|png|ico|map)$ {
        proxy_pass http://ohif:80;

        proxy_set_header Host $host;
    }

    location /assets/ {
        proxy_pass http://ohif:80;

        proxy_set_header Host $host;
    }

    # =========================
    # ORTHANC
    # =========================
    location /orthanc/ {
        proxy_pass http://orthanc:8042/;

        proxy_set_header Host $host;

        rewrite ^/orthanc/(.*)$ /$1 break;
    }
}
