server {
    listen 80;
    server_name vizionxvet.conexao46.com.br;

    client_max_body_size 500M;

    # =========================
    # OHIF
    # =========================
    location /viewer/ {
        proxy_pass http://ohif:80/;

        proxy_set_header Host $host;

        rewrite ^/viewer/(.*)$ /$1 break;
    }

    # =========================
    # OHIF assets fixos
    # =========================
    location = /app-config.js {
        proxy_pass http://ohif:80/app-config.js;
    }

    location = /manifest.json {
        proxy_pass http://ohif:80/manifest.json;
    }

    location = /init-service-worker.js {
        proxy_pass http://ohif:80/init-service-worker.js;
    }

    location = /app.bundle.css {
        proxy_pass http://ohif:80/app.bundle.css;
    }

    location ~ ^/app\.bundle\..*\.js$ {
        proxy_pass http://ohif:80;
    }

    # =========================
    # assets/chunks do OHIF
    # =========================
    location ~* ^/(.*)\.(js|css|png|ico|map)$ {
        proxy_pass http://ohif:80;

        proxy_set_header Host $host;
    }

    location /assets/ {
        proxy_pass http://ohif:80;

        proxy_set_header Host $host;
    }

    # =========================
    # Orthanc
    # =========================
    location /orthanc/ {
        proxy_pass http://orthanc:8042/;

        proxy_set_header Host $host;

        rewrite ^/orthanc/(.*)$ /$1 break;
    }

    # =========================
    # Django
    # =========================
    location / {
        proxy_pass http://django-web:8000;

        proxy_set_header Host $host;
    }
}